.github/workflows/test.yml
CHANGELOG.md

Accuracy test

---

.github/workflows/test.yml
CHANGELOG.md
README.md
mytimer/__main__.py
mytimer/functions.py
otherfiles/version_check.py
setup.py

close #2 
close #5 
Version 0.2

Version 0.2

---

CHANGELOG.md
README.md
mytimer/__init__.py
mytimer/__main__.py
mytimer/functions.py
mytimer/params.py
otherfiles/version_check.py

- Infinite timer mode added
- Parameters moved to `params.py`

Infinite Timer

---

CHANGELOG.md
README.md
otherfiles/version_check.py

Minor edits

---

CHANGELOG.md
README.md
mytimer/params.py
otherfiles/version_check.py
setup.cfg
setup.py

Version 0.5

---

CHANGELOG.md
mytimer/__main__.py

#26 
- Inputs type changed to `int`

Inputs type

---

otherfiles/RELEASE.md

Release instructions

---

CHANGELOG.md
README.md
mytimer/params.py
otherfiles/version_check.py
setup.py

Version 0.6

---

CHANGELOG.md
README.md
mytimer/params.py
otherfiles/version_check.py
setup.py

Version 0.7

---

CHANGELOG.md
README.md
mytimer/params.py
otherfiles/version_check.py
setup.py

Version 0.8

---

CHANGELOG.md
PROGRAMS.md
mytimer/params.py

#44 
New programs added:
+ `work`
+ `short-break`
+ `long-break`

New programs added {`work`, `short-break`, `long-break`}

---

CHANGELOG.md
README.md
mytimer/params.py
otherfiles/version_check.py
setup.py

close #44 
close #46 
close #51 
Version 0.9

Version 0.9

---

CHANGELOG.md
mytimer/params.py

#57 
- `japanese-green-tea` program bug fixed

Program bug fix

---

.github/workflows/test.yml
CHANGELOG.md
README.md
mytimer/__main__.py
mytimer/functions.py
mytimer/params.py

#54 
`--programs-list` argument added to the main program.

`--programs-list` argument added

---

.github/workflows/test.yml
AUTHORS.md
CHANGELOG.md
README.md
mytimer/__main__.py
mytimer/functions.py
mytimer/params.py

#55 
Added the `--face-list` flag, showing all available faces for showing the time.

Add `--faces-list` flag

---

CHANGELOG.md
README.md
mytimer/params.py
otherfiles/version_check.py
setup.py

close #45 
close #54 
close #55 
close #57 
Version 1.0

Version 1.0

---

CHANGELOG.md
mytimer/params.py

#66
Zero padding added to the time showing format.

Zero padding added

---

CHANGELOG.md
PROGRAMS.md
README.md
mytimer/functions.py
mytimer/params.py

#76 #75 
I added two programs (`52_17` and `112_26`) similar to `pomodoro`.
I believe the implementation is truly suboptimal, but since I started using `mytimer` in my day-to-day schedule and wanted to have those other programs I decided to add them both in a PR. I believe we can enhance implementation quality by refactoring later.

New programs added

---

CHANGELOG.md
PROGRAMS.md
README.md
mytimer/functions.py
mytimer/params.py

#83 
- 1 new program added
1. `animedoro`
I will combine and improve the `animedoro_timer`, `_112_26_timer`, and `_52_17_timer` functions in a separate pull request.

AnimeDoro Timer

---

.github/CODE_OF_CONDUCT.md
CHANGELOG.md
README.md
SECURITY.md
dev-requirements.txt
otherfiles/RELEASE.md
otherfiles/version_check.py
setup.py

SECURITY.md

---

.github/workflows/test.yml
CHANGELOG.md
mytimer/functions.py
mytimer/params.py

- `two_step_timer` function added
- `animedoro_timer` function removed
- `_112_26_timer` function removed
- `_52_17_timer` function removed

Two step timer

---

.github/workflows/test.yml
CHANGELOG.md

Test duration

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/workflows/test.yml
CHANGELOG.md
README.md
SECURITY.md
mytimer/params.py
otherfiles/version_check.py
setup.py

Version 1.3

---

CHANGELOG.md
PROGRAMS.md
mytimer/params.py
otherfiles/RELEASE.md

- `mid-break` program added
- `long-break` program duration changed from `15 minutes` to `30 minutes`

Medium break

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
README.md
SECURITY.md
mytimer/params.py
otherfiles/version_check.py
setup.py

Version 1.4

---

CHANGELOG.md
README.md
mytimer/__main__.py
mytimer/functions.py

#20 
- `--keep-on` argument added
- `keep_on_timer` added

`--keep-on`

---

CHANGELOG.md
PROGRAMS.md
README.md
mytimer/params.py

- 2 new programs added
1. `rooibos-tea`
2. `yellow-tea`

New programs

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
README.md
SECURITY.md
mytimer/params.py
otherfiles/version_check.py
setup.py

Version 1.5

---

CHANGELOG.md
README.md
mytimer/functions.py
mytimer/params.py

- Default mode changed from `count-up` to `countdown`

Default mode

---

CHANGELOG.md
PROGRAMS.md
mytimer/params.py

- `white-tea` program duration changed from `10 minutes` to `3 minutes`
References:
1. https://worldteadirectory.com/know-tea-guide-tea-steeping-time/
2. https://artfultea.com/blogs/101/loose-leaf-tea-steep-time

`white-tea` program update

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
README.md
SECURITY.md
mytimer/params.py
otherfiles/version_check.py
setup.py

Version 1.6

---

.github/ISSUE_TEMPLATE/feature_request.yml
AUTHORS.md

Fix typo found via `typos --hidden --format brief`

ci : fix typo

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
README.md
SECURITY.md
mytimer/params.py
otherfiles/version_check.py
setup.py

Version 1.7

---

.github/workflows/test.yml
CHANGELOG.md
README.md
mytimer/__main__.py
mytimer/functions.py
mytimer/params.py

- Face random mode added
- `get_face` function added
- `show_faces_list` function updated

Face random mode

---

CHANGELOG.md
README.md
mytimer/__main__.py
mytimer/functions.py
mytimer/params.py

- Tone random mode added
- `get_tone` function added

Tone random mode

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
README.md
SECURITY.md
mytimer/params.py
otherfiles/version_check.py
setup.py

Version 1.8

---

CHANGELOG.md
TONES.md

`TONES.md`

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
README.md
SECURITY.md
mytimer/params.py
otherfiles/version_check.py
setup.py

Version 1.9

---

CHANGELOG.md
PROGRAMS.md
mytimer/params.py

- 1 new program added
1. `coffee-break`

Coffee break

---

mytimer/functions.py

This PR will add the `print_date_time` function so that printing the date and time before the message is done in a function and used more modularly during the program.

`print_date_time` Function Added

---

.github/workflows/test.yml
CHANGELOG.md
README.md
mytimer/__main__.py
mytimer/functions.py
mytimer/params.py

#106 
- `--hide-datetime` argument added
- Test system modified

`--hide-datetime`

---

CHANGELOG.md
PROGRAMS.md
mytimer/params.py

- 1 new program added
1. `meditation`

Meditation

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
README.md
SECURITY.md
mytimer/params.py
otherfiles/version_check.py
setup.py

Version 2.0

---

CHANGELOG.md
README.md
mytimer/__main__.py
mytimer/functions.py

#138 
- `--test-tone` argument added

`--test-tone`

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
README.md
SECURITY.md
mytimer/params.py
otherfiles/version_check.py
setup.py

fix #135 
fix #138 
Version 2.1

Version 2.1

---

.github/workflows/test.yml
CHANGELOG.md
README.md
dev-requirements.txt
mytimer/__main__.py
mytimer/functions.py
mytimer/params.py
requirements.txt

- `--date-system` argument added
- Test system modified
- `countdown_timer` and `countup_timer` functions updated

Date System

---

.github/workflows/test.yml
CHANGELOG.md
mytimer/__main__.py

- Input case sensitivity bug fixed

Case Sensitivity

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
README.md
SECURITY.md
mytimer/params.py
otherfiles/version_check.py
setup.py

Version 2.2

---

CHANGELOG.md
mytimer/__main__.py
mytimer/functions.py
otherfiles/version_check.py
setup.py

#153 
Type hints added to all modules of mytimer.

Type hints

---

.github/workflows/publish_pypi.yml
.github/workflows/test.yml
CHANGELOG.md
setup.py

- Test system modified
- `Python 3.6` support dropped

`Ubuntu-20.04` --> `Ubuntu-22.04`

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
README.md
SECURITY.md
mytimer/params.py
otherfiles/version_check.py
setup.py

fix #153 
fix #157 
Version 2.3

Version 2.3
